mymacros = {
"bm": [r"\boldsymbol{#1}", 1],    
"pdt": [r"{\frac{\partial #1}{\partial t}}", 1],
"pdx":[r"{\frac{\partial #1}{\partial x}}", 1],
"pdy":[r"{\frac{\partial #1}{\partial y}}", 1],
"pdz":[r"{\frac{\partial #1}{\partial z}}", 1],
"pdxi":[r"{\frac{\partial #1}{\partial \xi}}", 1],
"pdeta":[r"{\frac{\partial #1}{\partial \eta}}", 1],
"pdzeta":[r"{\frac{\partial #1}{\partial \zeta}}", 1],
"div":r"{\operatorname{div}}",
"eps":r"{\varepsilon}",
"tr":r"{\operatorname{tr}}",
"dev":r"{\operatorname{dev}}",
"curl":r"{\operatorname{curl}}",
"grad":r"{\nabla}",
"T":r"{\rm{T}}",
"I":r"{\operatorname{I}}",
"Re":r"{\operatorname{\rm{Re}}}",
"Pr":r"{\operatorname{\rm{Pr}}}",
"Ma":r"{\operatorname{\rm{Ma}}}",
"Fr":r"{\operatorname{\rm{Fr}}}",
"dl":[r"{#1^*}", 1],
"pdtdl":[r"{\frac{\partial #1}{\partial \dl{t}}}", 1],
"pdxdl":[r"{\frac{\partial #1}{\partial \dl{x}}}", 1],
"pdydl":[r"{\frac{\partial #1}{\partial \dl{y}}}", 1],
"pdzdl":[r"{\frac{\partial #1}{\partial \dl{z}}}", 1],
"jump":[r"{{[\![#1]\!]}}", 1],
"sym":[r"{{\rm sym} (#1) }", 1],
"skw":[r"{{\rm skw} (#1) }", 1],
"vec":[r"{\bm{#1}}", 1],
"mat":[r"{#1}", 1],
"rhoref":r"{\rho_{\rm{ref}}}",
"uref":r"{u_{\rm{ref}}}",
"Tref":r"{T_{\rm{ref}}}",
"muref":r"{\mu_{\rm{ref}}}",
"Lref":r"{L_{\rm{ref}}}",
"kref":r"{k_{\rm{ref}}}",
"uinf":r"{u_\infty}",
"cinf":r"{c_\infty}",
"muinf":r"{\mu_\infty}",
"kinf":r"{k_\infty}",
"rhoinf":r"{\rho_\infty}",
"Tinf":r"{T_\infty}",
"pinf":r"{p_\infty}",
"VEL":r"{\vec{u}}",
"HEAT":r"{\vec{q}}",
"TAU":r"{\mat{\tau}}",
"EPS":r"{\mat{\varepsilon}}",
"CVAR":r"{\vec{U}}",
"PVAR":r"{\vec{V}}",
"CHVAR":r"{\vec{W}}"}